spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true

#  h2:
#    console:
#      enabled: true
#      path: /h2
  datasource:
    #url: jdbc:h2:mem:~/testdb
    url: jdbc:mysql://127.0.0.1:3306/shop?characterEncoding=utf8&useSSL=false&autoReconnection=true
    username: root
    password: jjhh1231
    driverClassName: com.mysql.cj.jdbc.Driver